name: smart_isp
description: "Smart ISP Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  window_manager: ^0.3.8
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/login_bg.png
    - assets/signup_bg.png
    - assets/login.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
